"""Add foreign key to orders table

Revision ID: c641d3a7f2eb
Revises: 8c0b8a26d65b
Create Date: 2025-11-09 07:33:44.085520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c641d3a7f2eb'
down_revision: Union[str, None] = '8c0b8a26d65b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    # ### end Alembic commands ###

